services:
    Enhavo\Bundle\AppBundle\Toolbar\ToolbarManager:
        arguments:
            - '@security.authorization_checker'
            - '@Enhavo\Component\Type\FactoryInterface[ToolbarWidget]'

    Enhavo\Bundle\AppBundle\Toolbar\Type\BaseToolbarWidgetType:
        tags:
            - { name: enhavo_app.toolbar_widget }

    Enhavo\Bundle\AppBundle\Toolbar\Type\IconToolbarWidgetType:
        arguments:
            - '@translator'
            - '@router'
        tags:
            - { name: enhavo_app.toolbar_widget }

    Enhavo\Bundle\AppBundle\Toolbar\Type\QuickMenuToolbarWidgetType:
        arguments:
            - '@translator'
            - '@router'
        tags:
            - { name: enhavo_app.toolbar_widget }


    Enhavo\Bundle\AppBundle\Toolbar\Type\NewWindowToolbarWidgetType:
        arguments:
            - '@translator'
        tags:
            - { name: enhavo_app.toolbar_widget }
