framework:
    translator: { fallback: "%locale%" }
    validation:
        enabled: true
    session:
        cookie_lifetime: 25920000

enhavo_app:
    locale: "%locale%"
    template_paths:
        enhavo_app:
            path: '@EnhavoAppBundle/Resources/views'
            alias: 'EnhavoApp'
            priority: 10
